spring.application.name=Belajar Spring Restful API

spring.datasource.url=jdbc:postgresql://localhost:5432/belajar_spring_restful_api
spring.datasource.username=pgadmin
spring.datasource.password=P@ssw0rd#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=50


#PG_USERNAME=pgadmin
#PG_PASSWORD=P@ssw0rd#
#PG_URL=jdbc:postgresql://localhost:5432/belajar_spring_restful_api
#PG_HOST=localhost
#PG_PORT=5432
#PG_DBNAME=belajar_spring_restful_api